# Generated by Django 3.0.4 on 2020-05-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
