# Generated by Django 3.0.4 on 2020-06-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200510_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=150)),
                ('problem', models.CharField(max_length=20)),
                ('langUsed', models.CharField(max_length=20)),
                ('verdict', models.IntegerField(default=0)),
                ('runTime', models.IntegerField(default=0)),
                ('memUsed', models.IntegerField(default=0)),
            ],
        ),
    ]
