# Generated by Django 3.0.4 on 2020-06-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_submission_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='log',
            field=models.TextField(null=True),
        ),
    ]
